config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :mebles
  get 'zapiszsie', to: 'users#nowy'
  resources :users, except: [:nowy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, expect: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :meble
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :mebles, through: :article_categories
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
end

app/models/meble.rb
class Meble < ApplicationRecord
    has_many :article_categories
    has_many :categories, through: :article_categories
    belongs_to :user
    validates :nazwa, presence: true, length: {minimum:1, maximum:100}
    validates :rodzaj, presence: true, length: {minimum:1, maximum:100}
    validates :opis, presence: true, length: {minimum:1, maximum:100}
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :mebles, dependent: :destroy
    validates :username, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
    has_secure_password
    has_many_attached :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user  
    end

    def require_user
        if !logged_in?
            flash[:alert] = "Musisz być zalogowany, aby wykonać tą akcję"
            redirect_to administracja_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index,:show]

    def new
        @category = Category.new
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Kategorię poprawnie edytowano!"
            redirect_to @category
        else
            render 'edit'
        end
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Zapisano kategorię"
            redirect_to @category
        else
            render 'new'
        end
    end
    
    def show
        @category = Category.find(params[:id])
        @mebles= @category.mebles.paginate(page: params[:page], per_page: 5)
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Tylko admin może wykonać tą akcję!"
            redirect_to categories_path
        end
    end
end

app/controllers/mebles_controller.rb
class MeblesController < ApplicationController
    before_action :set_meble, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def show

    end

    def index
        @mebles = Meble.paginate(page: params[:page], per_page: 5)
    end

    def create
        @meble = Meble.new(meble_params)
        @meble.user = current_user
        if @meble.save
            flash[:notice] = "Mebel poprawnie utworzono!"
            redirect_to @meble
        else
            render 'new'
        end
    end

    def new
        @meble = Meble.new
    end

    def edit
       
    end

    def update
    
        if @meble.update(meble_params)
            flash[:notice] = "Poprawnie edytowano mebel."
            redirect_to @meble
        else
            render 'edit'
        end
    end

    def destroy
     
        @meble.destroy
        redirect_to mebles_path
    end

    private
    
    def set_meble
        @meble = Meble.find(params[:id])
    
    end

    def meble_params
        params.require(:meble).permit(:nazwa,:rodzaj,:opis, category_ids: [])
    end

    def require_same_user
        if current_user != @meble.user && !current_user.admin?
            flash[:alert] = "Możesz edytowac tylko swój mebel cwaniaku!"
            redirect_to @meble
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to mebles_path if logged_in?
    end
    def about

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Zalogowano pomyślnie"
            redirect_to user
        else
            flash.now[:alert] = "Nieprawidłowe hasło lub email"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Wylogowano użytkownika"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def nowy
        @user = User.new
    end

    def show
        @mebles = @user.mebles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @user = User.paginate(page: params[:page], per_page: 5)
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Jesteś nowym użytkownikiem #{@user.username} ziom!"
            redirect_to mebles_path
        else
            render 'nowy'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Profil i dodane meble usunięto"
        redirect_to mebles_path
    end

    def edit

    end

    def update

        if @user.update(user_params)
            flash[:notice] = "Poprawnie zaktualizowano użytkownika"
            redirect_to @user
        else
            render 'edit'
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password, images: [])
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "Możesz edytować lub usunąć tylko swój profil cwaniaku!"
            redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-secondary mr-1" %>

app/views/categories/_form.html.erb
  <%= render 'shared/errors', obj: @category %>
        <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-secondary rounded", local: true)  do |f| %>
        <div class="form-group row">
            <%= f.label :name, "Kategoria:", class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Podaje nazwę kategorii" %>
            </div>
        </div>

 

          <div class="form-group row justify-content-center">
            <%= f.submit "Dodaj kategorię", class: "btn btn-outline-success" %>         
          </div>
        <% end %>

app/views/categories/edit.html.erb
<h1 class = "text-center mt-4">Edytuj nazwę kateorii</h1>

<div class="container">
  <div class="row justify-content-center">
      <div class="col-10">
        <%= render 'form' %>
      </div>
      <div class="mb-3">
        <%= link_to '[ Anuluj i wróc do kategorii ]', category_path(@category), class: "text-secondary" %>
      </div>
  </div>
    
</div>

app/views/categories/index.html.erb
<h1 class = "text-center mt-4">Kategoria</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
    <% @categories.each do |category|%>
        <div class="row justify-content-md-center">
        <div class="col-4 mt-4">
 <div class="card shadow mb-5 bg-white rounded">
        <div class="card-body">
            <h5 class="card-title">Nazwa: <%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.mebles.count, "mebli") %></p>
        </div>
        <div class="card-footer text-muted"> 
            <a> Stworzono: <%= time_ago_in_words(category.created_at) %>, 
            <% if category.updated_at == nil %>
            Nie edytowano
            <% else %>
            Edytowano: <%= time_ago_in_words(category.updated_at) %>
            <% end %>
            </a>
        </div>
        </div>
        </div>
        </div>
    <% end %>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class = "text-center mt-4">Tworzenie nowej kategorii</h1>

<div class="container">
  <div class="row justify-content-center">
      <div class="col-10">
        <%= render 'form' %>
      </div>
      <div class="mb-3">
        <%= link_to '[ Anuluj i wróc do listy kategorii ]', categories_path, class: "text-secondary" %>
      </div>
  </div>
    
</div>
     

app/views/categories/show.html.erb
<h1 class = "text-center mt-4">Kategoria <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
        <%= link_to "Edytuj nazwę kategorii", edit_category_path(@category), class: "btn btn-primary" %>
    </div>
<% end %>
</p>
<h3 class = "text-center mt-4">Meble</h3>

<div class="flickr_pagination">
    <%= will_paginate @mebles, :container => false %>
</div>
<%= render 'mebles/mebles'%>

<div class="flickr_pagination mb-4">
    <%= will_paginate @mebles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Wszelkie prawa &copy; zastrzeżone!</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg|%>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_pasek.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Mebles", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Strona domowa <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <%= link_to "Użytkownicy", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Lista mebli", mebles_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Wylogowanie", logout_path, class: "nav-link", method: :delete %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profil - <%= current_user.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Wyświetl profil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edytuj profil", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Usuń profil", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Jesteś pewien?"} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Logowanie", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Zapisz się!", zapiszsie_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Meble
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <%= link_to "Dodaj nowy mebel", new_meble_path, class: "dropdown-item" %>
             <% end %>
            <%= link_to "Lista mebli", mebles_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Realizacje</a>
            <a class="dropdown-item" href="https://www.youtube.com/watch?v=feA64wXhbjo">Cennik</a>
            <a class="dropdown-item" href="https://www.youtube.com/watch?v=3e1-2ZMsOzI">O mnie</a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Kategorie
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in? && current_user.admin? %>
                <%= link_to "Dodaj nową kategorię", new_category_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Lista kategorii", categories_path, class: "dropdown-item" %>
        </li>

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Szukaj" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Szukaj</button>
      </form>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meblownia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column"> 
  
    <%= render 'layouts/pasek' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/mebles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
      <div class="col-10">
        <%= render 'shared/errors', obj: @meble %>
        <%= form_with(model: @meble, class: "shadow p-3 mb-3 bg-secondary rounded", local: true)  do |f| %>
        <div class="form-group row">
            <%= f.label :nazwa, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :nazwa, class: "form-control shadow rounded", placeholder: "Nazwa mebla" %>
            </div>
        </div>

        <div class="form-group row">
              <%= f.label :rodzaj, class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :rodzaj, class: "form-control shadow rounded", placeholder: "Rodzaj mebla" %>
              </div>
        </div>

          <div class="form-group row">
              <%= f.label :opis, class: "col-2 col-form-label text-light" %>
              <div class="col-10"> 
                <%= f.text_area :opis, rows: 5, class: "form-control shadow rounded", placeholder: "Opis mebla" %>
              </div>
          </div>

          <div class="form-group row">
              <%= f.label :kategoria, class: "col-2 col-form-label text-light" %>
              <div class="col-10"> 
                <%= f.collection_select(:category_ids, Category.all, :id, :name,
                {prompt: "Wybierz kategorię z listy poniżej"}, {multiple: true, size: 3, class: "custom-select shadow rounded"}) %>
              </div>
          </div>

          <div class="form-group row justify-content-center">
              <% if @akcja == "edit" %>
                  <%= f.submit 'Edytuj', class: "btn btn-outline-success" %>
              <% else %>
                  <%= f.submit 'Utwórz', class: "btn btn-outline-success" %>
              <% end %>
              
        </div>
        <% end %>
      </div>
      <div class="mb-3">
        <%= link_to '[ Anuluj i wróc do listy mebli ]', mebles_path, class: "text-secondary" %>
      </div>
  </div>
    
</div>
     

app/views/mebles/_mebles.html.erb
<div class="container">
    <% @mebles.each do |meb|%>
        <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
 <div class="card shadow mb-5 bg-white rounded">
  <div class="card-header font-italic">
            <% if meb.user %>
                Dodano przez - <%= link_to meb.user.username, user_path(meb.user) %>
            <% end %>
            <% if meb.categories.any?%>
                <div class="mt-2">
                    <%= render meb.categories %>
                </div>
            <% end %>
        </div>
        <div class="card-body">
            <h5 class="card-title">Nazwa: <%= link_to meb.nazwa, meble_path(meb), class: "text-success" %></h5>
            <h5 class="card-title">Rodzaj: <%= truncate(meb.rodzaj, length: 100) %></h5>
                <button type="button" class="collapsibles">Opis mebla</button>
                <div class="content">
                <p class="card-text"><%= meb.opis %></p>
                </div>
            <a><%= link_to "Pokaż", meble_path(meb), class: "btn btn-primary" %></a>
            <% if logged_in? && (meb.user == current_user || current_user.admin?) %>
                <a><%= link_to "Edytuj", edit_meble_path(meb), class: "btn btn-primary" %></a>
                <a><%= link_to "Usuń", meble_path(meb), class: "btn btn-primary", method: :delete, data: {confirm: "Na pewno usunąć?"}  %></a>
            <% end %>
        </div>
        <div class="card-footer text-muted"> 
            <a> Stworzono: <%= time_ago_in_words(meb.created_at) %>, 
            <% if meb.update_at == nil %>
            Nie edytowano
            <% else %>
            Edytowano: <%= time_ago_in_words(meb.update_at) %>
            <% end %>
            </a>
        </div>
        </div>
        </div>
        </div>
    <% end %>
</div>

app/views/mebles/edit.html.erb
<h1 class = "text-center mt-4">Edycja elementów</h1>
<% @akcja = "edit"%>
<%= render 'form' %>

app/views/mebles/index.html.erb
<h1 class = "text-center mt-4">Lista mebli</h1>

<div class="flickr_pagination">
    <%= will_paginate @mebles, :container => false %>
</div>
<%= render 'mebles' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @mebles, :container => false %>
</div>

<script>
    var coll = document.getElementsByClassName("collapsibles");
    var i;

    for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function() {
        this.classList.toggle("activek");
        var content = this.nextElementSibling;
        if (content.style.maxHeight){
        content.style.maxHeight = null;
        } else {
        content.style.maxHeight = content.scrollHeight + "px";
        }
    });
    }
</script>

app/views/mebles/new.html.erb
<h1 class = "text-center mt-4">Dodawanie nowego mebla</h1>
<% @akcja = "new"%>
<%= render 'form' %>

app/views/mebles/show.html.erb
<h2 class = "text-center mt-4"><%= @meble.nazwa %></h2>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                    <% if @meble.user %>
                        Dodano przez - <%= link_to @meble.user.username, user_path(@meble.user) %>
                    <% end %>
                    <% (0...@meble.user.images.count).each do |image|%>
                        <div style="width:200px; height:200px;" class = "rounded mx-auto d-block">
                            <%= link_to image_tag(@meble.user.images[image], style: 'display: block; margin: auto; width: 70%;'), @meble.user %>
                        </div>
                    <% end %>
                    <% if @meble.categories.any?%>
                        <div class="mt-2">
                            <%= render @meble.categories %>
                        </div>
                    <% end %>
                </div>
        <div class="card-body">
            <h5 class="card-title">Rodzaj: <%= @meble.rodzaj %></h5>
            <button type="button" class="collapsibles">Opis mebla</button>
            <div class="content">
                <div class="card-text text-left"> <%= simple_format(@meble.opis) %></div>
                </div>
                <% if logged_in? && (@meble.user == current_user || current_user.admin?) %>
                    <a><%= link_to "Edytuj", edit_meble_path(@meble), class: "btn btn-primary" %></a>
                    <a><%= link_to "Usuń", meble_path(@meble), class: "btn btn-primary", method: :delete, data: {confirm: "Na pewno usunąć?"}  %></a>
                <% end %>
            </div>
        <div class="card-footer text-muted"> 
            <a> Stworzono: <%= time_ago_in_words(@meble.created_at) %>, 
            <% if @meble.update_at == nil %>
            Nie edytowano
            <% else %>
            Edytowano: <%= time_ago_in_words(@meble.update_at) %>
            <% end %>
            </a>
        </div>
        </div>
        </div>
        </div>
</div>
<script>
    var coll = document.getElementsByClassName("collapsibles");
    var i;

    for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function() {
        this.classList.toggle("activek");
        var content = this.nextElementSibling;
        if (content.style.maxHeight){
        content.style.maxHeight = null;
        } else {
        content.style.maxHeight = content.scrollHeight + "px";
        }
    });
    }
</script>

app/views/pages/about.html.erb
<h1>Strona o mnie!

<p>
    <%= link_to 'Lista mebli', mebles_path %>
    <%= link_to 'Strona domowa', root_path %>
</p>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center">
    <h1 class="display-4 text-success font-weight-bold">MEBLES</h1>
    <p class="lead text-success" id="naglowek2">Robimy meble od lat, przekonaj się i sprawdź naszą ofertę.</p>
    <hr class="my-4">
    <p id="naglowek3">Sprawdź nas!</p>
    <p>
    <a class="btn btn-outline-success btn-lg" id="przycisk" href="/mebles" role="button">Lista mebli</a>
    <%= link_to "Zapisz się!", zapiszsie_path, class: "btn btn-outline-success btn-lg", id: "przycisk" %>
  </p>
  </div>
</div>
<p>
    <!--%= link_to 'Lista mebli', mebles_path %>
    #<%= link_to 'Strona o mnie', about_path %-->
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %> 
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Nie można zapisać <%= obj.class.name.downcase %> z powodu następujących błędów:</h4>
        <ul> 
            <% obj.errors.full_messages.each do |msg| %> 
                <li><%= msg %></li> 
            <% end %> 
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1 class = "text-center mt-4">Edycja użytkownika</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class = "text-center mt-4">Lista użytkowników</h1>

<div class="flickr_pagination">
    <%= will_paginate @user, :container => false %>
</div>


<div class="container">
    <% @user.each do |user|%>
        <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
 <div class="card shadow mb-5 bg-white rounded">
  <div class="card-header font-italic">
            <%= link_to user.username, user_path(user) %>
        </div>
        <div class="card-body">
            <h5 class="card-title">
                <p>
                <% (0...user.images.count).each do |image|%>
                    <div style="width:200px; height:200px;" class = "rounded mx-auto d-block">
                        <%= image_tag(user.images[image], style: 'display: block; margin: auto; width: 80%;') %>
                    </div>
                <% end %>
                </p>
            </h5>
            <p>
            <h5 class="card-text mt-3"> 
                <% if user.mebles.count == 0 %>
                    <%= "Użytkownik nie dodał mebli" %>
                <% elsif user.mebles.count == 1 %>
                    <%= "Liczba dodanych mebli: #{user.mebles.count} mebel" %>
                <% elsif user.mebles.count > 1 && user.mebles.count <= 4 %>
                    <%= "Liczba dodanych mebli: #{user.mebles.count} meble" %>
                <% elsif user.mebles.count > 4 && user.mebles.count <= 21 %>
                    <%= "Liczba dodanych mebli: #{user.mebles.count} mebli" %>
                <% elsif user.mebles.count > 21 %>
                    <%= "Liczba dodanych mebli: #{user.mebles.count} mebli" %>
                <% end %>
            </h5>
            </p>
            
                <a><%= link_to "Profil", user, class: "btn btn-primary" %></a>
            <% if logged_in? %>
                <% if user == current_user %>    
                    <a><%= link_to "Edytuj", edit_user_path(user), class: "btn btn-primary" %></a>
                <% end %>
                <%if current_user.admin?%>
                    <%= link_to "Usuń użytkownika", user_path(user), class: "btn btn-outline-danger",
                    method: :delete, data: {confirm: "Czy na pewno chcesz usunąć użytkownika i powiązane meble?"} %>
                <% end %>
            <% end %>
        </div>
        <div class="card-footer text-muted"> 
            <a> Dołączono: <%= time_ago_in_words(user.created_at) %></a>
        </div>
        </div>
        </div>
        </div>
    <% end %>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @user, :container => false %>
</div>

app/views/users/nowy.html.erb
<h1 class = "text-center mt-4">Logowanie do aplikacji</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class = "text-center mt-4">Profil użytkownika <%= @user.username %></h1>

<p>
<% (0...@user.images.count).each do |image|%>
    <div style="width:300px; height:300px;" class = "rounded mx-auto d-block">
        <%= image_tag(@user.images[image], style: 'display: block; margin: auto; width: 80%;') %>
    </div>
<% end %>
</p>
<p>
<% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
        <%= link_to "Edytuj profil", edit_user_path(@user), class: "btn btn-primary" %>
    </div>
<% end %>
</p>
<h3 class = "text-center mt-4">Meble</h3>

<div class="flickr_pagination">
    <%= will_paginate @mebles, :container => false %>
</div>
<%= render 'mebles/mebles'%>

<div class="flickr_pagination mb-4">
    <%= will_paginate @mebles, :container => false %>
</div>